### ISSUE TITLE
Add pyopenssl to gsutil builder

### ISSUE THREAD

**Issue by MattiaPance** [GoogleCloudPlatform/cloud-sdk-docker#230]
Hi all,
I first opened this issue in the cloud-builders repository (https://github.com/GoogleCloudPlatform/cloud-builders/issues/734), but @bendory suggested me to transfer the request here.

I want to use the gsutil signurl command within a Cloud Build step with the cloud-sdk-docker builder, but when I tried it, the builder failed with:

'CommandException: The signurl command requires the pyopenssl library (try pip install pyopenssl or easy_install pyopenssl)'

Is it possible to fix it by adding pyopenssl to the cloud-sdk-docker builder?

**Comment by bendory** [comment]
@MattiaPance I suggest leaving aside the question of the `gsutil` Cloud Builder.

Please provide an example here that uses `gcr.io/google.com/cloudsdktool/cloud-sdk` and demonstrates the issue you are experiencing. In the [prior issue](https://github.com/GoogleCloudPlatform/cloud-builders/issues/734#issuecomment-724180483), you had provided this:

```
$ sudo docker run -it gcr.io/google.com/cloudsdktool/cloud-sdk gsutil signurl key.json gs://pizza-pizza-pizza/parisim.png
CommandException: The signurl command requires the pyopenssl library (try pip install pyopenssl or easy_install pyopenssl)
```

Is that everything that the Cloud SDK team needs to understand and reproduce this problem?

**Comment by MattiaPance** [comment]
@bendory yes, thanks. 
You wrote the problem correctly

**Comment by willfaris** [comment]
This should be fixed in the 320.0.0 release scheduled for December 8th, 2020.

**Comment by doron-cohen** [comment]
Hi, I encountered this issue and after pulling the latest `google/cloud-sdk:alpine` image I saw that it isn't fixed there. Is there a reason not to fix it in the Alpine variation too?

**Comment by willfaris** [comment]
Alpine image should have the same ability to sign urls out of the box starting with release 324.0.0
